# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Drilldown on neuropsych domains.
#'
#' This function uses the R Highcharter package and drilldown function to "drill down" on neuropsychological domains and test scores.
#'
#' @param patient Patient name
#' @param data Dataset to use
#' @import highcharter
#' @importFrom rlang .data
#' 
#' @return 
#' A drilldown plot
#'
#' @export
#' @examples
#' datafile <- system.file("neurocog.csv", package = "brainworkupr")
#' neurocog <- read.csv(datafile, encoding = "UTF-8")
#' patient <- "Biggie"
#' drill(patient = patient, data = neurocog)
drill <- function(patient = NULL, data = c("neurocog", "neurobehav")) {
  ## Level 1
  ## Domain scores
  # 1. create mean z-scores for domain
  zMean <- NULL
  name <- NULL
  ncog1 <- data %>%
    dplyr::group_by(.data$domain) %>%
    dplyr::summarize(zMean = mean(.data$z), zPct = mean(.data$percentile)) %>%
    dplyr::mutate(range = NA)
  ncog1$zMean <- round(ncog1$zMean, 2L)
  ncog1$zPct <- round(ncog1$zPct, 0L)
  ncog1 <-
    ncog1 %>%
    dplyr::mutate(
      range = dplyr::case_when(
        zPct >= 98 ~ "Exceptionally High",
        zPct %in% 91:97 ~ "Above Average",
        zPct %in% 75:90 ~ "High Average",
        zPct %in% 25:74 ~ "Average",
        zPct %in% 9:24 ~ "Low Average",
        zPct %in% 2:8 ~ "Below Average",
        zPct < 2 ~ "Exceptionally Low",
        TRUE ~ as.character(range)
      )
    )
  
  # 2. sort hi to lo
  ncog1 <- dplyr::arrange(ncog1, dplyr::desc(zMean))
  
  # 3. create data.table with new column with domain name lowercase
  ncog_level1_status <- tibble::tibble(
    name = ncog1$domain,
    y = ncog1$zMean,
    y2 = ncog1$zPct,
    range = ncog1$range, 
    drilldown = tolower(name)
  )
  
  ## Level 2
  ## Subdomain scores
  ## function to create second level of drilldown (subdomain scores)
  ncog_level2_drill <-
    lapply(unique(data$domain), function(x_level) {
      ncog2 <- subset(data, data$domain %in% x_level)
      
      # same as above
      ncog2 <-
        ncog2 %>%
        dplyr::group_by(.data$subdomain) %>%
        dplyr::summarize(zMean = mean(.data$z), zPct = mean(.data$percentile)) %>%
        dplyr::mutate(range = NA)
      
      # round z-score to 1 decimal
      ncog2$zMean <- round(ncog2$zMean, 2L)
      ncog2$zPct <- round(ncog2$zPct, 0L)
      ncog2 <-
        ncog2 %>%
        dplyr::mutate(
          range = dplyr::case_when(
            zPct >= 98 ~ "Exceptionally High",
            zPct %in% 91:97 ~ "Above Average",
            zPct %in% 75:90 ~ "High Average",
            zPct %in% 25:74 ~ "Average",
            zPct %in% 9:24 ~ "Low Average",
            zPct %in% 2:8 ~ "Below Average",
            zPct < 2 ~ "Exceptionally Low",
            TRUE ~ as.character(range)
          )
        )
      
      # 2. sort hi to lo
      ncog2 <- dplyr::arrange(ncog2, dplyr::desc(zMean))
      
      # 3. create data.table with new column with domain name lowercase
      ncog_level2_status <- tibble::tibble(
        name = ncog2$subdomain,
        y = ncog2$zMean,
        y2 = ncog2$zPct,
        range = ncog2$range,
        drilldown = tolower(paste(x_level, name, sep = "_"))
      )
      
      list(
        id = tolower(x_level),
        type = "column",
        data = highcharter::list_parse(ncog_level2_status)
      )
    })
  
  
  ## Level 3
  ## Narrow subdomains
  ## reuse function
  ncog_level3_drill <-
    lapply(unique(data$domain), function(x_level) {
      ncog2 <- subset(data, data$domain %in% x_level)
      
      # reuse function but with y_level
      lapply(unique(ncog2$subdomain), function(y_level) {
        # 1. create mean z-scores for subdomain
        # ncog3 becomes pronoun for domain
        ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
        
        ncog3 <- ncog3 %>%
          dplyr::group_by(.data$narrow) %>%
          dplyr::summarize(zMean = mean(.data$z), zPct = mean(.data$percentile)) %>%
          dplyr::mutate(range = NA)
        
        # round z-score to 1 decimal
        ncog3$zMean <- round(ncog3$zMean, 2L)
        ncog3$zPct <- round(ncog3$zPct, 0L)
        ncog3 <-
          ncog3 %>%
          dplyr::mutate(
            range = dplyr::case_when(
              zPct >= 98 ~ "Exceptionally High",
              zPct %in% 91:97 ~ "Above Average",
              zPct %in% 75:90 ~ "High Average",
              zPct %in% 25:74 ~ "Average",
              zPct %in% 9:24 ~ "Low Average",
              zPct %in% 2:8 ~ "Below Average",
              zPct < 2 ~ "Exceptionally Low",
              TRUE ~ as.character(range)
            )
          )
        
        ncog3 <- dplyr::arrange(ncog3, dplyr::desc(zMean))
        
        ncog_level3_status <- tibble::tibble(
          name = ncog3$narrow,
          y = ncog3$zMean,
          y2 = ncog3$zPct,
          range = ncog3$range,
          drilldown = tolower(paste(x_level, y_level, name, sep = "_"))
        )
        
        list(
          id = tolower(paste(x_level, y_level, sep = "_")),
          type = "column",
          data = highcharter::list_parse(ncog_level3_status)
        )
      })
    }) %>% unlist(recursive = FALSE)
  
  
  ## Level 4
  ## Scale scores
  ## reuse both functions
  ncog_level4_drill <-
    lapply(unique(data$domain), function(x_level) {
      ncog2 <- subset(data, data$domain %in% x_level)
      
      lapply(unique(ncog2$subdomain), function(y_level) {
        ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
        
        lapply(unique(ncog3$narrow), function(z_level) {
          ncog4 <- subset(ncog3, ncog3$narrow %in% z_level)
          
          ncog4 <-
            ncog4 %>%
            dplyr::group_by(.data$scale) %>%
            dplyr::summarize(zMean = mean(.data$z), zPct = mean(.data$percentile)) %>%
            dplyr::mutate(range = NA)
          
          # round z-score to 1 decimal
          ncog4$zMean <- round(ncog4$zMean, 2L)
          ncog4$zPct <- round(ncog4$zPct, 0L)
          ncog4 <-
            ncog4 %>%
            dplyr::mutate(
              range = dplyr::case_when(
                zPct >= 98 ~ "Exceptionally High",
                zPct %in% 91:97 ~ "Above Average",
                zPct %in% 75:90 ~ "High Average",
                zPct %in% 25:74 ~ "Average",
                zPct %in% 9:24 ~ "Low Average",
                zPct %in% 2:8 ~ "Below Average",
                zPct < 2 ~ "Exceptionally Low",
                TRUE ~ as.character(range)
              )
            )
          
          ncog4 <- dplyr::arrange(ncog4, dplyr::desc(zMean))
          
          ncog_level4_status <- tibble::tibble(
            name = ncog4$scale,
            y = ncog4$zMean,
            y2 = ncog4$zPct,
            range = ncog4$range
          )
          
          list(
            id = tolower(paste(x_level, y_level, z_level, sep = "_")),
            type = "column",
            data = highcharter::list_parse(ncog_level4_status)
          )
        })
      }) %>% unlist(recursive = FALSE)
    }) %>% unlist(recursive = FALSE)
  
  
  theme_merge <- 
    highcharter::hc_theme_merge(
      highcharter::hc_theme_monokai(),
      highcharter::hc_theme_darkunica())
  
  ## Tooltip
  x <- c("Name", "Score", "Percentile", "Range")
  y <- c("{point.name}", "{point.y}", "{point.y2}", "{point.range}")
  tt <- highcharter::tooltip_table(x, y)
  
  ## Create drilldown bar plot zscores
  plot <-
    highcharter::highchart() %>%
    highcharter::hc_title(text = patient,
             style = list(fontSize = "15px")) %>%
    highcharter::hc_add_series(ncog_level1_status,
                  type = "bar",
                  name = "Neuropsychological Test Scores",
                  highcharter::hcaes(x = name, y = y)) %>%
    highcharter::hc_xAxis(
      type = "category",
      title = list(text = "Domain"),
      categories = name
    ) %>%
    highcharter::hc_yAxis(
      title = list(text = "z-Score (M = 0, SD = 1)"),
      labels = list(format = "{value}")
    ) %>%
    highcharter::hc_tooltip(pointFormat = tt,
               useHTML = TRUE,
               valueDecimals = 1) %>%
    highcharter::hc_plotOptions(series = list(
      colorByPoint = TRUE,
      allowPointSelect = TRUE,
      dataLabels = TRUE
    )) %>%
    highcharter::hc_drilldown(
      allowPointDrilldown = TRUE,
      series = c(ncog_level2_drill,
                 ncog_level3_drill,
                 ncog_level4_drill)
    ) %>%
    highcharter::hc_colorAxis(minColor = "red",
                 maxColor = "blue") %>%
    highcharter::hc_add_theme(theme_merge) %>%
    highcharter::hc_chart(style = list(fontFamily = "Cabin"),
             backgroundColor = list("gray"))
  plot
}
