# WARNING - Generated by {fusen} from /dev/flat_make_df.Rmd: do not edit by hand

#' Make data frame
#' @return
#' A data frame
#' @export
#'
#' @examples
#' df <- make_df(
#'   params = list(
#'     test = "tmt",
#'     test_name = "Trail Making Test",
#'     scale = "Trails B",
#'     raw_score = 55,
#'     score = 50,
#'     score_type = "t_score",
#'     domain = "Attention/Executive",
#'     subdomain = "Processing Speed",
#'     narrow = "Set-Shifting",
#'     pass = "Planning",
#'     verbal = "Nonverbal",
#'     timed = "Timed",
#'     mean = 50,
#'     stdev = 10,
#'     reliability = .95,
#'     test_type = "npsych_test"
#'   )
#' )
#' 
make_df <- function(params = NULL) {
  df <- tidytable::tidytable(
    test = (params$test),
    test_name = (params$test_name),
    test_type = (params$test_type),
    scale = (params$scale),
    raw_score = as.numeric(params$raw_score),
    score = as.numeric(params$score),
    ci_95 = NA,
    score_adj = NA,
    ci_95_lower = NA,
    ci_95_upper = NA,
    percentile = NA,
    range = NA,
    range_lower = NA,
    range_upper = NA,
    score_type = (params$score_type),
    domain = (params$domain),
    subdomain = (params$subdomain),
    narrow = (params$narrow),
    pass = (params$pass),
    verbal = (params$verbal),
    timed = (params$timed),
    absort =
      paste0(
        tolower(params$test),
        "_",
        tolower(params$scale),
        "_",
        seq_len(1)
      ),
    description = NA,
    result = NA
  )
}
